---
- name: Ensure SVN packages are installed.
  yum: pkg={{ item }} state=installed
  with_items:
    - mod_dav_svn
    - subversion
  when: ansible_os_family == 'RedHat'

# To be used once Debian is supported in all dependencies.
# - name: Ensure SVN packages are installed (Debian).
#   apt: pkg={{ item }} state=installed
#   with_items:
#     - subversion
#     - libapache2-svn
#   when: ansible_os_family == 'Debian'

- name: Ensure svn home folder exists.
  file: path={{ svn_repository_home }} state=directory

- name: Copy subversion configuration file.
  template: >
    src=subversion.conf.j2
    dest=/etc/httpd/conf.d/subversion.conf
    owner=root
    group=root
  notify: restart apache

- name: Create a initial repository.
  command: >
    svnadmin create {{ svn_initial_repository }}
    chdir={{ svn_repository_home }}
    creates={{ svn_repository_home }}/{{ svn_initial_repository }}/README.txt
  when: svn_create_initial_repo

- name: Set ownership for svn directories.
  file: >
    path={{ svn_repository_home }}
    owner=apache
    group=apache
    recurse=yes
  notify: restart apache

- name: Creates Subversion directory
  file: path=/var/svn state=directory

# TODO: Is there any way to specify `--root {{ svn_repository_home }}`? Environment?
- name: Ensure svnserve service is started.
  service: name=svnserve state=started enabled=yes
